locals {
  create_in_bucket_actions = [
    "s3:PutObject",
    "s3:PutObjectAcl",
    "s3:PutObjectLegalHold",
    "s3:PutObjectRetention",
    "s3:PutObjectTagging",
    "s3:PutObjectVersionAcl",
    "s3:ReplicateObject",
    "s3:RestoreObject"
  ]
  read_in_bucket_actions = [
    "s3:GetObject",
    "s3:GetObjectAcl",
    "s3:GetObjectLegalHold",
    "s3:GetObjectRetention",
    "s3:GetObjectTagging",
    "s3:GetObjectTorrent",
    "s3:GetObjectVersion",
    "s3:GetObjectVersionAcl",
    "s3:GetObjectVersionTorrent"
  ]
  delete_in_bucket_actions = [
    "s3:DeleteObject",
    "s3:DeleteObjectVersion",
    "s3:ReplicateDelete",
  ]
  create_bucket_actions = [
    "s3:CreateBucket",
    "s3:PutAccelerateConfiguration",
    "s3:PutBucketAcl",
    "s3:PutBucketCORS",
    "s3:PutBucketEncryption",
    "s3:PutBucketLogging",
    "s3:PutBucketNotification",
    "s3:PutBucketObjectLockConfiguration",
    "s3:PutBucketPolicy",
    "s3:PutBucketRequestPayment",
    "s3:PutBucketTagging",
    "s3:PutBucketVersioning",
    "s3:PutBucketWebsite",
    "s3:PutEncryptionConfiguration",
    "s3:PutLifecycleConfiguration",
    "s3:PutPublicAccessBlock",
    "s3:PutAccountPublicAccessBlock",
    "s3:PutReplicationConfiguration",
    "s3:ReplicateObject",
    "s3:RestoreObject"
  ]
  read_bucket_actions = [
    "s3:GetAccelerateConfiguration",
    "s3:GetAccountPublicAccessBlock",
    "s3:GetBucketAcl",
    "s3:GetBucketCORS",
    "s3:GetBucketEncryption",
    "s3:GetBucketLocation",
    "s3:GetBucketLogging",
    "s3:GetBucketNotification",
    "s3:GetBucketObjectLockConfiguration",
    "s3:GetBucketPolicy",
    "s3:GetBucketRequestPayment",
    "s3:GetBucketTagging",
    "s3:GetBucketVersioning",
    "s3:GetBucketWebsite",
    "s3:GetEncryptionConfiguration",
    "s3:GetLifecycleConfiguration",
    "s3:GetPublicAccessBlock",
    "s3:GetReplicationConfiguration",
    "s3:ListAllMyBuckets",
    "s3:ListBucket",
    "s3:ListBucketMultipartUploads",
    "s3:ListBucketVersions",
    "s3:ListMultipartUploadParts"
  ]
  delete_bucket_actions = [
    "s3:DeleteBucket",
    "s3:DeleteBucketEncryption",
    "s3:DeleteBucketPolicy",
    "s3:DeleteBucketWebsite",
    "s3:DeletePublicAccessBlock",
    "s3:ReplicateDelete"
  ]
}
