#!/bin/bash

if ! command -v asdf &>/dev/null; then
  echo "asdf is not installed. Please install asdf first: https://asdf-vm.com/"
  exit 1
fi

SCRIPTS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PROJECT_DIR="$(dirname "$SCRIPTS_DIR")"
TEST_DIR="${PROJECT_DIR}/tests"

cd "${TEST_DIR}/stack" || exit 1

set -e
asdf plugin add python
asdf plugin add terraform

asdf install

printf '%s\n' "Installing stack..."
pip install 'moto[server]>=5.0,<6.0'

printf '%s\n' "stack installed successfully."
