#!/usr/bin/env bash

set -euo pipefail

SCRIPTS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PROJECT_DIR="$(dirname "$SCRIPTS_DIR")"
TEST_DIR="${PROJECT_DIR}/tests"

cd "${TEST_DIR}/stack" || exit 1

curl --fail http://localhost:4566/_ministack/health >/dev/null 2>&1 || ministack -d

printf "%s\n" "${PWD}"

terraform init
terraform apply -auto-approve
